import type { MapDataTileObject } from "zep-script";
import { getObjectByParam1 } from "./utils";

// ===============================
// 🎃 CLÉS DES OBJETS
// ===============================
export const HALLOWEEN_OBJECT_KEYS = {
  // 🧪 HALL A
  HALL_A: {
    PORTE_A2: "HALL_A_PORTE_A2",
    DECOR_CHAUDRON: "HALL_A_DECOR_CHAUDRON",
    CHAUVE_SOURIS: "HALL_A_CHAUVE_SOURIS",
  },
  A1_POTIONS: {
    CITROUILLE: "A1_POTIONS_CITROUILLE",
    CHAUDRON: "A1_POTIONS_CHAUDRON",
    LIVRE: "A1_POTIONS_LIVRE",
  },
  A2_BIBLIOTHEQUE: {
    LIVRE_MAUDIT: "A2_BIBLIOTHEQUE_LIVRE_MAUDIT",
    BOUGIE: "A2_BIBLIOTHEQUE_BOUGIE",
  },
  A4_ASTRONOMIE: {
    TELESCOPE: "A4_ASTRONOMIE_TELESCOPE",
    ETOILE: "A4_ASTRONOMIE_ETOILE",
  },
  A5_METAMORPHOSE: {
    CENDRE: "A5_METAMORPHOSE_CENDRE",
  },

  // ⚡ HALL B
  HALL_B: {
    GENERATEUR: "HALL_B_GENERATEUR",
    ECLAIR: "HALL_B_ECLAIR",
    PANNEAU: "HALL_B_PANNEAU",
  },
  B1_DORTOIR: {
    LIT: "B1_DORTOIR_LIT",
    FANTOME: "B1_DORTOIR_FANTOME",
  },
  B2_ELECTRICAL: {
    GENERATEUR: "B2_ELECTRICAL_GENERATEUR",
    INTERRUPTEUR: "B2_ELECTRICAL_INTERRUPTEUR",
  },
  B3_CUISINE: {
    COUTEAU: "B3_CUISINE_COUTEAU",
    CHAUDRON: "B3_CUISINE_CHAUDRON",
  },
  B4_BAINS: {
    MIROIR: "B4_BAINS_MIROIR",
    SQUELETTE: "B4_BAINS_SQUELETTE",
  },

  // 🌿 HALL C
  HALL_C: {
    PORTAIL: "HALL_C_PORTAIL",
    TOILE: "HALL_C_TOILE",
    CITROUILLE: "HALL_C_CITROUILLE",
  },
    // 🌿 HALL C
  HALL_C_POUR_C2: {
    PORTAIL: "HALL_C_POUR_C2_PORTAIL",
    TOILE: "HALL_C_POUR_C2_TOILE",
    CITROUILLE: "HALL_C_POUR_C2_CITROUILLE",
  },
  C1_SERRE: {
    PLANTE: "C1_SERRE_PLANTE",
    PLANTE2: "C1_SERRE_PLANTE2",
    PLANTE3: "C1_SERRE_PLANTE3",
    PLANTE4: "C1_SERRE_PLANTE4",
    CITROUILLE: "C1_SERRE_CITROUILLE",
  },
  C2_FORET_INTERDITE: {
    CITROUILLE: "C2_FORET_INTERDITE_CITROUILLE",
    CITROUILLE2: "C2_FORET_INTERDITE_CITROUILLE2",
    CITROUILLE3: "C2_FORET_INTERDITE_CITROUILLE3",
    ARAIGNE1: "C2_FORET_INTERDITE_ARAIGNE1",
    ARAIGNE2: "C2_FORET_INTERDITE_ARAIGNE2",
  },
  C3_LABYRINTHE: {
    CITROUILLE: "C3_LABYRINTHE_CITROUILLE",
    CITROUILLE2: "C3_LABYRINTHE_CITROUILLE2",
    CITROUILLE3: "C3_LABYRINTHE_CITROUILLE3",
    CITROUILLE4: "C3_LABYRINTHE_CITROUILLE4",
    CITROUILLE5: "C3_LABYRINTHE_CITROUILLE5",
    RAT: "C3_LABYRINTHE_RAT",
    RAT2: "C3_LABYRINTHE_RAT2",
    CRANE: "C3_LABYRINTHE_CRANE",
    FANTOME: "C3_LABYRINTHE_FANTOME",
  },
  C4_ENCLOS: {
    LICORNE: "C4_ENCLOS_LICORNE",
    SQUELETTE: "C4_ENCLOS_SQUELETTE",
  },
  C5_CABANE_HAGRID: {
    FEU: "C5_CABANE_HAGRID_FEU",
    CHIEN: "C5_CABANE_HAGRID_CHIEN",
  },

  // ☠️ HALL D
  HALL_D: {
    CITROUILLE: "HALL_D_CITROUILLE",
    CITROUILLE2: "HALL_D_CITROUILLE2",
    TOMBE: "HALL_D_TOMBE",
    TOMBE2: "HALL_D_TOMBE2",
    CRANE: "HALL_D_CRANE",
    CRANE2: "HALL_D_CRANE2",
    CRANE3: "HALL_D_CRANE3",
    CRANE4: "HALL_D_CRANE4",
    CRANE5: "HALL_D_CRANE5",
  },
  D1_CRYPTE: {
    RAT: "D1_CRYPTE_RAT",
    RAT2: "D1_CRYPTE_RAT2",
    TROU: "D1_CRYPTE_TROU",
    SQUELETTE: "D1_CRYPTE_SQUELETTE",
  },
  D2_COULOIR: {
    TROU: "D2_COULOIR_TROU",
    TROU2: "D2_COULOIR_TROU2",
    TROU3: "D2_COULOIR_TROU3",
    TROU4: "D2_COULOIR_TROU4",
    TROU5: "D2_COULOIR_TROU5",
    TROU6: "D2_COULOIR_TROU6",
    TROU7: "D2_COULOIR_TROU7",
    TROU8: "D2_COULOIR_TROU8",
    TROU9: "D2_COULOIR_TROU9",
  },
  D3_CACHOT: {
    ARAIGNE: "D3_CACHOT_ARAIGNE",
    TONNEAU: "D3_CACHOT_TONNEAU",
    ARMOIRE: "D3_CACHOT_ARMOIRE",
  },
  D4_SACRIFICE: {
    BAINS: "D4_SACRIFICE_BAINS",
    ANTRE: "D4_SACRIFICE_ANTRE",
  },
} as const;



// // Objets résolus directement avec cast pour TS
// export const OBJECTS: Record<string, MapDataTileObject | null> = {
//   // Voitures
//   [OBJECT_KEYS.A1_POTIONS.CITROUILLE]: getObjectByParam1(OBJECT_KEYS.A1_POTIONS.CITROUILLE) as unknown as MapDataTileObject,
//   [OBJECT_KEYS.A5_METAMORPHOSE.CENDRE]: getObjectByParam1(OBJECT_KEYS.A5_METAMORPHOSE.CENDRE) as unknown as MapDataTileObject,
 
// };

// ===============================
// 💀 OBJETS RÉSOLUS
// ===============================
export const HALLOWEEN_OBJECT: Record<string, MapDataTileObject | null> = Object.fromEntries(
  Object.values(HALLOWEEN_OBJECT_KEYS).flatMap(group =>
    Object.values(group).map(key => [key, getObjectByParam1(key) as unknown as MapDataTileObject])
  )
);