import type { MapDataTileObject } from "zep-script";
import { getObjectByParam1 } from "./utils";

// Clés des objets
export const OBJECT_KEYS = {
  SALLE1: { VOITURE1: "SALLE1_VOITURE1", VOITURE2: "SALLE1_VOITURE2", PORTE: "SALLE1_PORTE" },
  SALLE2: { VOITURE1: "SALLE2_VOITURE1", VOITURE2: "SALLE2_VOITURE2", PORTE: "SALLE2_PORTE" },
  SALLE3: { VOITURE1: "SALLE3_VOITURE1", VOITURE2: "SALLE3_VOITURE2", PORTE: "SALLE3_PORTE" },
  SALLE4: { VOITURE1: "SALLE4_VOITURE1", VOITURE2: "SALLE4_VOITURE2", PORTE: "SALLE4_PORTE" },
  SALLE5: { VOITURE1: "SALLE5_VOITURE1", VOITURE2: "SALLE5_VOITURE2", PORTE: "SALLE5_PORTE" },
  SALLE6: { VOITURE1: "SALLE6_VOITURE1", VOITURE2: "SALLE6_VOITURE2", PORTE: "SALLE6_PORTE" },
  SALLE7: { VOITURE1: "SALLE7_VOITURE1", VOITURE2: "SALLE7_VOITURE2", PORTE: "SALLE7_PORTE" },
  SALLE8: { VOITURE1: "SALLE8_VOITURE1", VOITURE2: "SALLE8_VOITURE2", PORTE: "SALLE8_PORTE" },
  SALLE9: { VOITURE1: "SALLE9_VOITURE1", VOITURE2: "SALLE9_VOITURE2", PORTE: "SALLE9_PORTE" },
  SALLE10: { VOITURE1: "SALLE10_VOITURE1", VOITURE2: "SALLE10_VOITURE2", PORTE: "SALLE10_PORTE" },
  SALLE11: { VOITURE1: "SALLE11_VOITURE1", VOITURE2: "SALLE11_VOITURE2", PORTE: "SALLE11_PORTE" },
  SALLE12: { VOITURE1: "SALLE12_VOITURE1", VOITURE2: "SALLE12_VOITURE2", PORTE: "SALLE12_PORTE" },
  SALLE13: { VOITURE1: "SALLE13_VOITURE1", VOITURE2: "SALLE13_VOITURE2", PORTE: "SALLE13_PORTE" },
  SALLE14: { VOITURE1: "SALLE14_VOITURE1", VOITURE2: "SALLE14_VOITURE2", PORTE: "SALLE14_PORTE" },
  SALLE15: { VOITURE1: "SALLE15_VOITURE1", VOITURE2: "SALLE15_VOITURE2", PORTE: "SALLE15_PORTE" },
  SALLE16: { VOITURE1: "SALLE16_VOITURE1", VOITURE2: "SALLE16_VOITURE2", PORTE: "SALLE16_PORTE" },
  SALLE17: { VOITURE1: "SALLE17_VOITURE1", VOITURE2: "SALLE17_VOITURE2", PORTE: "SALLE17_PORTE" },
  SALLE18: { VOITURE1: "SALLE18_VOITURE1", VOITURE2: "SALLE18_VOITURE2", PORTE: "SALLE18_PORTE" },
  SALLE19: { VOITURE1: "SALLE19_VOITURE1", VOITURE2: "SALLE19_VOITURE2", PORTE: "SALLE19_PORTE" },
  SALLE20: { VOITURE1: "SALLE20_VOITURE1", VOITURE2: "SALLE20_VOITURE2", PORTE: "SALLE20_PORTE" },
} as const;


// Objets résolus directement avec cast pour TS
export const OBJECTS: Record<string, MapDataTileObject | null> = {
  // Voitures
  [OBJECT_KEYS.SALLE1.VOITURE1]: getObjectByParam1(OBJECT_KEYS.SALLE1.VOITURE1) as unknown as MapDataTileObject,
  [OBJECT_KEYS.SALLE1.VOITURE2]: getObjectByParam1(OBJECT_KEYS.SALLE1.VOITURE2) as unknown as MapDataTileObject,
  [OBJECT_KEYS.SALLE2.VOITURE1]: getObjectByParam1(OBJECT_KEYS.SALLE2.VOITURE1) as unknown as MapDataTileObject,
  [OBJECT_KEYS.SALLE2.VOITURE2]: getObjectByParam1(OBJECT_KEYS.SALLE2.VOITURE2) as unknown as MapDataTileObject,
  //.....

  // Portes
  [OBJECT_KEYS.SALLE1.PORTE]: getObjectByParam1(OBJECT_KEYS.SALLE1.PORTE) as unknown as MapDataTileObject,
  [OBJECT_KEYS.SALLE2.PORTE]: getObjectByParam1(OBJECT_KEYS.SALLE2.PORTE) as unknown as MapDataTileObject,
};
